'use strict';
const DB_NAME='bf-finance-5',DB_VERSION=1,STORE='state',STATE_KEY='app';
const EXPENSE_CATS=['Moradia','Energia','Água','Internet/Telefone','Mercado','Transporte','Saúde','Educação','Filhos/Família','Lazer','Restaurantes','Assinaturas','Compras','Dívidas','Impostos/Taxas','Outros'];
const INCOME_CATS=['Salário','Hora extra','Renda extra','Investimentos','Reembolso','Outras receitas'];
const DEFAULT_STATE={version:5,transactions:[],budgets:[],goals:[],theme:'dark',migrated:false,createdAt:new Date().toISOString()};
let db,state=structuredClone(DEFAULT_STATE);const $=id=>document.getElementById(id),BRL=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2),clone=v=>JSON.parse(JSON.stringify(v)),n=v=>Number.isFinite(Number(v))?Number(v):0,fmt=v=>BRL.format(n(v)),monthKey=d=>String(d||'').slice(0,7),today=()=>new Date().toISOString().slice(0,10),currentMonth=()=>today().slice(0,7),isPaid=t=>t.status==='paid';
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function monthLabel(m){if(!/^\d{4}-\d{2}$/.test(m||''))return'—';const[y,mo]=m.split('-');return new Date(+y,+mo-1,1).toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}function addMonths(s,i){const d=new Date(s+'T12:00:00');d.setMonth(d.getMonth()+i);return d.toISOString().slice(0,10)}
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}function dbGet(k){return new Promise((resolve,reject)=>{const r=db.transaction(STORE,'readonly').objectStore(STORE).get(k);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}function dbSet(k,v){return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(v,k);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}async function save(){state.version=5;await dbSet(STATE_KEY,clone(state))}function normalizeState(s){const o=Object.assign({},DEFAULT_STATE,s||{});o.transactions=Array.isArray(o.transactions)?o.transactions:[];o.budgets=Array.isArray(o.budgets)?o.budgets:[];o.goals=Array.isArray(o.goals)?o.goals:[];o.theme=o.theme==='light'?'light':'dark';return o}
async function migrateLegacy(){if(state.transactions.length||state.budgets.length||state.goals.length||state.migrated)return false;let changed=false;try{const old=JSON.parse(localStorage.getItem('financeiro-pro-3')||'null');if(old&&Array.isArray(old.entries)){old.entries.forEach(e=>state.transactions.push({id:e.id||uid(),type:e.type==='income'?'income':'expense',date:e.date||today(),due:e.due||'',description:e.description||'Lançamento importado',category:e.category||'Outros',amount:Math.abs(n(e.amount)),method:'Importado',status:'paid',note:'Migrado automaticamente',recurrenceId:''}));(old.goals||[]).forEach(g=>state.goals.push({id:g.id||uid(),name:g.name||'Meta importada',target:Math.max(0,n(g.target)),current:Math.max(0,n(g.current)),type:'Objetivo',due:''}));changed=true}}catch{}try{const h=JSON.parse(localStorage.getItem('pfHistory')||'[]');if(Array.isArray(h)&&h.length){h.forEach(x=>{const d=(x.month||currentMonth())+'-01';if(n(x.income)>0)state.transactions.push({id:uid(),type:'income',date:d,due:'',description:'Receitas importadas',category:'Outras receitas',amount:n(x.income),method:'Importado',status:'paid',note:'Resumo mensal importado',recurrenceId:''});if(n(x.expenses)>0)state.transactions.push({id:uid(),type:'expense',date:d,due:'',description:'Despesas importadas',category:'Outros',amount:n(x.expenses),method:'Importado',status:'paid',note:'Resumo mensal importado',recurrenceId:''})});changed=true}}catch{}state.migrated=true;await save();return changed}
function txForMonth(m){return state.transactions.filter(t=>monthKey(t.date)===m)}function summary(m){const tx=txForMonth(m),paid=tx.filter(isPaid),income=paid.filter(t=>t.type==='income').reduce((a,t)=>a+n(t.amount),0),expense=paid.filter(t=>t.type==='expense').reduce((a,t)=>a+n(t.amount),0),pending=tx.filter(t=>t.status==='pending'&&t.type==='expense').reduce((a,t)=>a+n(t.amount),0);return{income,expense,pending,balance:income-expense,tx}}function totalBudget(m){return state.budgets.filter(b=>b.month===m).reduce((a,b)=>a+n(b.limit),0)}
